EXPERIMENT:
  LOGIT_STAND: True
KD:
  TEMPERATURE: 4
  LOSS:
    T_WEIGHT: 0.1
    KD_WEIGHT: 7
    QUEUE_SIZE: 6000
SOLVER:
  PRINT_FREQ: 50
  SAVE_STEP: 1
PRELOAD_TEACHER_LOGIT: True
PRELOAD_BATCH: 1024
LOG:
  FREQUENCY: 1
  IJB_FREQUENCY: 3
DDP:
  USE_DDP: False
  WORLD_SIZE: 2
EVAL:
  DATASET_PATH : "/data/tx/MS1MV2"
  EVAL_DATASET : ['lfw', 'agedb_30', 'cfp_fp']
  EVAL_EPOCH : True
  MODEL_PATH: "./models/train_data/"